export const oneUserRoute = ({ id }: { id: string }) => `/users/${id}`;
export const loginRoute = () => '/login';
export const homeRoute = () => '/';
export const meRoute = () => '/me';
export const registerRequestCreateRoute = () => '/register-request';
export const registerRequestsAdminRoute = () => '/admin/register-requests';
export const completeRegistrationRoute = () => '/complete-registration';
export const directionsRoute = () => '/directions';
export const legalFormsRoute = () => '/legal-forms';
export const departmentsRoute = () => '/departments';
export const positionsRoute = () => '/positions';
export const companiesRoute = () => '/companies';
